
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pry1_ci;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LLAVESCUADCIERRA = 47;
  public static final int PLUSPLUS = 35;
  public static final int STRING_LITERAL = 52;
  public static final int POWER = 29;
  public static final int CHAR = 13;
  public static final int L_BOOLEANO = 50;
  public static final int PARENTESISCIERRA = 41;
  public static final int FIN_EXPRESION = 3;
  public static final int SEMI = 44;
  public static final int GREATER_THAN_OR_EQ = 38;
  public static final int INT = 15;
  public static final int L_FLOTANTE = 49;
  public static final int FOR = 9;
  public static final int MINUS = 26;
  public static final int GREATER_THAN = 36;
  public static final int LESS_THAN_OR_EQ = 39;
  public static final int SYS_READ = 21;
  public static final int PARENTESISABRE = 40;
  public static final int L_CHAR = 51;
  public static final int DO_WHILE = 8;
  public static final int L_ENTERO = 48;
  public static final int BOOL = 12;
  public static final int PLUS = 23;
  public static final int MAIN = 2;
  public static final int IF = 4;
  public static final int LLAVESCORCHETECIERRA = 43;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 34;
  public static final int RETURN = 11;
  public static final int TRUE = 17;
  public static final int SYS_PRINT = 20;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int COMENTARIO = 19;
  public static final int MODULO = 30;
  public static final int NEGACION = 31;
  public static final int EQEQ = 22;
  public static final int BREAK = 10;
  public static final int EQ = 24;
  public static final int DIVI = 27;
  public static final int TIMES = 25;
  public static final int ELSE = 5;
  public static final int NOT_EQ = 28;
  public static final int WHILE = 7;
  public static final int LLAVESCORCHETEABRE = 42;
  public static final int Identificador = 53;
  public static final int FLOAT = 14;
  public static final int CONJUNCION = 32;
  public static final int STRING = 16;
  public static final int LLAVESCUADABRE = 46;
  public static final int DISYUNCION = 33;
  public static final int FALSE = 18;
  public static final int LESS_THAN = 37;
  public static final int ELIF = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "FIN_EXPRESION",
  "IF",
  "ELSE",
  "ELIF",
  "WHILE",
  "DO_WHILE",
  "FOR",
  "BREAK",
  "RETURN",
  "BOOL",
  "CHAR",
  "FLOAT",
  "INT",
  "STRING",
  "TRUE",
  "FALSE",
  "COMENTARIO",
  "SYS_PRINT",
  "SYS_READ",
  "EQEQ",
  "PLUS",
  "EQ",
  "TIMES",
  "MINUS",
  "DIVI",
  "NOT_EQ",
  "POWER",
  "MODULO",
  "NEGACION",
  "CONJUNCION",
  "DISYUNCION",
  "MINUSMINUS",
  "PLUSPLUS",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_THAN_OR_EQ",
  "LESS_THAN_OR_EQ",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVESCORCHETEABRE",
  "LLAVESCORCHETECIERRA",
  "SEMI",
  "COMA",
  "LLAVESCUADABRE",
  "LLAVESCUADCIERRA",
  "L_ENTERO",
  "L_FLOTANTE",
  "L_BOOLEANO",
  "L_CHAR",
  "STRING_LITERAL",
  "Identificador"
  };
}

